-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Heather Demo by heather.ready+demo@sqldbm.com *


-- ************************************** table_1
CREATE TABLE table_1
(

);

