-- ************************** SqlDBM: Redshift **************************
-- * Generated by SqlDBM: Redshift Sample, v3 by hazal.sener@sqldbm.com *


-- ************************************** HOTELBNB.HOTELS
CREATE TABLE HOTELBNB.HOTELS
(
 CITY_CODE varchar(3),
 HOTEL_ID  decimal(38,0),
 etl_id    timestamp NOT NULL -- From template: "Template_w_etl"

);


-- ************************************** EDW.DimScenario
CREATE TABLE EDW.DimScenario
(
 ScenarioKey  decimal(38,0) IDENTITY ( 1, 1 ),
 ScenarioName varchar(50),
 CreatedBy    varchar(50) NOT NULL,
 CreatedDate  timestamp NOT NULL,
 UpdatedDate  timestamp NOT NULL,
 UpdatedBy    varchar(50) NOT NULL,
 TestCol      varchar(50) NOT NULL,
 etl_id       timestamp NOT NULL, -- From template: "Template_w_etl"

 CONSTRAINT PK_DimScenario PRIMARY KEY ( ScenarioKey )
);

COMMENT ON TABLE EDW.DimScenario IS 'Dimension Scenario';

COMMENT ON COLUMN EDW.DimScenario.ScenarioKey IS 'Scenario Identifier';
COMMENT ON COLUMN EDW.DimScenario.ScenarioName IS 'Name of the Scenario';
COMMENT ON COLUMN EDW.DimScenario.CreatedBy IS 'Who Created this Scenario';
COMMENT ON COLUMN EDW.DimScenario.CreatedDate IS 'Scenario Creation Date';


-- ************************************** EDW.DimSalesTerritory
CREATE TABLE EDW.DimSalesTerritory
(
 SalesTerritoryKey          decimal(38,0) IDENTITY ( 1, 1 ),
 SalesTerritoryAlternateKey decimal(38,0),
 SalesTerritoryRegion       varchar(50) NOT NULL,
 SalesTerritoryCountry      varchar(50) NOT NULL,
 SalesTerritoryGroup        varchar(50),
 etl_id                     timestamp NOT NULL, -- From template: "Template_w_etl"

 CONSTRAINT PK_DimSalesTerritory PRIMARY KEY ( SalesTerritoryKey )
);

COMMENT ON TABLE EDW.DimSalesTerritory IS 'Sales Territory data';


-- ************************************** EDW.DimPromotion
CREATE TABLE EDW.DimPromotion
(
 PromotionKey             decimal(38,0) IDENTITY ( 1, 1 ),
 PromotionAlternateKey    decimal(38,0),
 EnglishPromotionName     varchar(255),
 SpanishPromotionName     varchar(255),
 FrenchPromotionName      varchar(255),
 DiscountPct              float,
 EnglishPromotionType     varchar(50),
 SpanishPromotionType     varchar(50),
 FrenchPromotionType      varchar(50),
 EnglishPromotionCategory varchar(50),
 SpanishPromotionCategory varchar(50),
 FrenchPromotionCategory  varchar(50),
 MinQty                   decimal(38,0),
 MaxQty                   decimal(38,0),
 etl_id                   timestamp NOT NULL, -- From template: "Template_w_etl"

 CONSTRAINT PK_DimPromotion PRIMARY KEY ( PromotionKey )
);


-- ************************************** EDW.DimProductCategory
CREATE TABLE EDW.DimProductCategory
(
 ProductCategoryKey          decimal(38,0) IDENTITY ( 1, 1 ),
 ProductCategoryAlternateKey decimal(38,0),
 EnglishProductCategoryName  varchar(50) NOT NULL,
 SpanishProductCategoryName  varchar(50) NOT NULL,
 FrenchProductCategoryName   varchar(50) NOT NULL,
 etl_id                      timestamp NOT NULL, -- From template: "Template_w_etl"

 CONSTRAINT PK_DimProductCategory PRIMARY KEY ( ProductCategoryKey )
);


-- ************************************** EDW.DimProduct
CREATE TABLE EDW.DimProduct
(
 ProductKey            decimal(38,0) IDENTITY ( 1, 1 ),
 ProductAlternateKey   varchar(25),
 WeightUnitMeasureCode varchar(3),
 SizeUnitMeasureCode   varchar(3),
 new_col               varchar(500) NOT NULL,
 EnglishProductName    varchar(50) NOT NULL,
 SpanishProductName    varchar(50),
 FrenchProductName     varchar(50),
 StandardCost          decimal(38,0),
 FinishedGoodsFlag     decimal(38,0) NOT NULL,
 Color                 varchar(15) NOT NULL,
 SafetyStockLevel      decimal(38,0),
 ReorderPoint          decimal(38,0),
 ListPrice             decimal(38,0),
 Size                  varchar(50),
 SizeRange             varchar(50),
 Weight                float,
 DaysToManufacture     decimal(38,0),
 ProductLine           varchar(2),
 DealerPrice           decimal(38,0),
 Class                 varchar(2),
 Style                 varchar(2),
 ModelName             varchar(50),
 EnglishDescription    varchar(400),
 FrenchDescription     varchar(400),
 ChineseDescription    varchar(400),
 ArabicDescription     varchar(400),
 HebrewDescription     varchar(400),
 ThaiDescription       varchar(400),
 GermanDescription     varchar(400),
 JapaneseDescription   varchar(400),
 TurkishDescription    varchar(400),
 Status                varchar(7),
 pk                    decimal NOT NULL,
 etl_id                timestamp NOT NULL, -- From template: "Template_w_etl"

 CONSTRAINT PK_DimProduct PRIMARY KEY ( ProductKey )
);


-- ************************************** EDW.DimDepartmentGroup
CREATE TABLE EDW.DimDepartmentGroup
(
 DepartmentGroupKey       decimal(38,0) IDENTITY ( 1, 1 ),
 ParentDepartmentGroupKey decimal(38,0),
 DepartmentGroupName      varchar(50),
 etl_id                   timestamp NOT NULL, -- From template: "Template_w_etl"

 CONSTRAINT PK_DimDepartmentGroup PRIMARY KEY ( DepartmentGroupKey )
);

COMMENT ON TABLE EDW.DimDepartmentGroup IS 'Dimension for Department groups';


-- ************************************** EDW.DimDate
CREATE TABLE EDW.DimDate
(
 DateKey              decimal(38,0) NOT NULL,
 FullDateAlternateKey date NOT NULL,
 DayNumberOfWeek      decimal(38,0) NOT NULL,
 EnglishDayNameOfWeek varchar(10) NOT NULL,
 SpanishDayNameOfWeek varchar(10) NOT NULL,
 FrenchDayNameOfWeek  varchar(10) NOT NULL,
 DayNumberOfMonth     decimal(38,0) NOT NULL,
 DayNumberOfYear      decimal(38,0) NOT NULL,
 WeekNumberOfYear     decimal(38,0) NOT NULL,
 EnglishMonthName     varchar(10) NOT NULL,
 SpanishMonthName     varchar(10) NOT NULL,
 FrenchMonthName      varchar(10) NOT NULL,
 MonthNumberOfYear    decimal(38,0) NOT NULL,
 CalendarQuarter      decimal(38,0) NOT NULL,
 CalendarYear         decimal(38,0) NOT NULL,
 CalendarSemester     decimal(38,0) NOT NULL,
 FiscalQuarter        decimal(38,0) NOT NULL,
 FiscalYear           decimal(38,0) NOT NULL,
 FiscalSemester       decimal(38,0) NOT NULL,
 etl_id               timestamp NOT NULL, -- From template: "Template_w_etl"

 CONSTRAINT PK_DimDate PRIMARY KEY ( DateKey )
);

COMMENT ON TABLE EDW.DimDate IS 'Dimension for Date time';


-- ************************************** EDW.DimCurrency
CREATE TABLE EDW.DimCurrency
(
 CurrencyKey          decimal(38,0) IDENTITY ( 1, 1 ),
 CurrencyAlternateKey varchar(3) NOT NULL,
 CurrencyName         varchar(50) NOT NULL,
 etl_id               timestamp NOT NULL, -- From template: "Template_w_etl"

 CONSTRAINT PK_DimCurrency PRIMARY KEY ( CurrencyKey )
);

COMMENT ON TABLE EDW.DimCurrency IS 'Dimension for Currency Data';

COMMENT ON COLUMN EDW.DimCurrency.CurrencyKey IS 'Currency Identifier';
COMMENT ON COLUMN EDW.DimCurrency.CurrencyAlternateKey IS 'Alternate Currency Identifier';
COMMENT ON COLUMN EDW.DimCurrency.CurrencyName IS 'Name of the Currency';


-- ************************************** EDW.DimAccount
CREATE TABLE EDW.DimAccount
(
 AccountKey                    decimal(38,0) IDENTITY ( 1, 1 ),
 ParentAccountKey              decimal(38,0),
 AccountCodeAlternateKey       decimal(38,0),
 ParentAccountCodeAlternateKey decimal(38,0),
 AccountDescription            varchar(50),
 AccountType                   varchar(50),
 Operator                      varchar(50),
 CustomMembers                 varchar(300),
 ValueType                     varchar(50),
 CustomMemberOptions           varchar(200),
 etl_id                        timestamp NOT NULL, -- From template: "Template_w_etl"

 CONSTRAINT PK_DimAccount PRIMARY KEY ( AccountKey )
);

COMMENT ON TABLE EDW.DimAccount IS 'Holds all Account information';

COMMENT ON COLUMN EDW.DimAccount.AccountKey IS 'Unique Identifier of the Account data';
COMMENT ON COLUMN EDW.DimAccount.ParentAccountKey IS 'Identifier of parent Account';


-- ************************************** HOTELBNB.DESTINATIONS
CREATE TABLE HOTELBNB.DESTINATIONS
(
 DESTINATION_ID               varchar(3) NOT NULL,
 DESTINATION_NAME             varchar(1000),
 CITY_CODE                    varchar(3),
 COUNTRY_CODE                 varchar(3),
 COUNTRY_NAME                 varchar(1000),
 COMMERCIAL_FINANCE_REGION    varchar(1000),
 COMMERCIAL_FINANCE_SUBREGION varchar(1000),
 HOTEL_DEST_REGION            varchar(1000),
 HOTEL_DEST_SUBREGION         varchar(1000),
 HOTEL_DEST_SUBREGION2        varchar(1000),
 BTB_SO_REGION                varchar(1000),
 BTB_SO_SUBREGION             varchar(1000),
 etl_id                       timestamp NOT NULL, -- From template: "Template_w_etl"

 CONSTRAINT DESTINATIONS_PK PRIMARY KEY ( DESTINATION_ID )
);


-- ************************************** EDW.ChildDemo_Test
CREATE TABLE EDW.ChildDemo_Test
(
 ChildDemo_TestId decimal(38,0) NOT NULL,
 CreatedBy        varchar(50) NOT NULL,
 CreatedDate      timestamp NOT NULL,
 UpdatedDate      timestamp NOT NULL,
 UpdatedBy        varchar(50) NOT NULL,
 TestintDBSN      varchar(50) NOT NULL,
 etl_id           timestamp NOT NULL -- From template: "Template_w_etl"

);


-- ************************************** HOTELBNB.BOOKINGS
CREATE TABLE HOTELBNB.BOOKINGS
(
 BOOKING_ID    varchar(12) NOT NULL,
 HOTEL_ID      decimal(38,0) NOT NULL,
 RN            decimal(38,0),
 CREATION_DATE date,
 etl_id        timestamp NOT NULL, -- From template: "Template_w_etl"

 CONSTRAINT PK_1 PRIMARY KEY ( BOOKING_ID, HOTEL_ID )
);


-- ************************************** EDW.FactProductInventory
CREATE TABLE EDW.FactProductInventory
(
 ProductKey   decimal(38,0) NOT NULL,
 DateKey      decimal(38,0) NOT NULL,
 MovementDate date NOT NULL,
 UnitCost     decimal(38,0) NOT NULL,
 UnitsIn      decimal(38,0) NOT NULL,
 UnitsOut     decimal(38,0) NOT NULL,
 UnitsBalance decimal(38,0) NOT NULL,
 etl_id       timestamp NOT NULL, -- From template: "Template_w_etl"
 new_col      decimal(18,0) NOT NULL,

 CONSTRAINT FK_FactProductInventory_443 FOREIGN KEY ( DateKey ) REFERENCES EDW.DimDate ( DateKey )
);


-- ************************************** EDW.FactCurrencyRate
CREATE TABLE EDW.FactCurrencyRate
(
 CurrencyKey  decimal(38,0) NOT NULL,
 DateKey      decimal(38,0) NOT NULL,
 AverageRate  float NOT NULL,
 EndOfDayRate float NOT NULL,
 etl_id       timestamp NOT NULL, -- From template: "Template_w_etl"

 CONSTRAINT FK_FactCurrencyRate_413 FOREIGN KEY ( CurrencyKey ) REFERENCES EDW.DimCurrency ( CurrencyKey ),
 CONSTRAINT FK_FactCurrencyRate_415 FOREIGN KEY ( DateKey ) REFERENCES EDW.DimDate ( DateKey )
);


-- ************************************** EDW.DimGeography
CREATE TABLE EDW.DimGeography
(
 GeographyKey             decimal(38,0) IDENTITY ( 1, 1 ),
 City                     varchar(30),
 StateProvinceCode        varchar(3),
 StateProvinceName        varchar(50),
 CountryRegionCode        varchar(3),
 EnglishCountryRegionName varchar(50),
 SpanishCountryRegionName varchar(50),
 FrenchCountryRegionName  varchar(50),
 PostalCode               varchar(15),
 SalesTerritoryKey        decimal(38,0),
 IpAddressLocator         varchar(15),
 etl_id                   timestamp NOT NULL, -- From template: "Template_w_etl"

 CONSTRAINT PK_DimGeography PRIMARY KEY ( GeographyKey )
);


-- ************************************** EDW.DimEmployee
CREATE TABLE EDW.DimEmployee
(
 EmployeeKey                          decimal(38,0) IDENTITY ( 1, 1 ),
 ParentEmployeeKey                    decimal(38,0),
 EmployeeNationalIDAlternateKey       varchar(15),
 ParentEmployeeNationalIDAlternateKey varchar(15),
 SalesTerritoryKey                    decimal(38,0),
 FirstName                            varchar(50) NOT NULL,
 LastName                             varchar(50) NOT NULL,
 MiddleName                           varchar(50),
 NameStyle                            decimal(38,0) NOT NULL,
 Title                                varchar(50),
 HireDate                             date,
 BirthDate                            date,
 LoginID                              varchar(256),
 EmailAddress                         varchar(50),
 Phone                                varchar(25),
 MaritalStatus                        varchar(1),
 EmergencyContactName                 varchar(50),
 EmergencyContactPhone                varchar(25),
 SalariedFlag                         decimal(38,0),
 Gender                               varchar(1),
 PayFrequency                         decimal(38,0),
 BaseRate                             decimal(38,0),
 VacationHours                        decimal(38,0),
 SickLeaveHours                       decimal(38,0),
 CurrentFlag                          decimal(38,0) NOT NULL,
 SalesPersonFlag                      decimal(38,0) NOT NULL,
 DepartmentName                       varchar(50),
 StartDate                            date,
 EndDate                              date,
 Status                               varchar(50),
 etl_id                               timestamp NOT NULL, -- From template: "Template_w_etl"

 CONSTRAINT PK_DimEmployee PRIMARY KEY ( EmployeeKey ),
 CONSTRAINT FK_DimEmployee_403 FOREIGN KEY ( ParentEmployeeKey ) REFERENCES EDW.DimEmployee ( EmployeeKey ),
 CONSTRAINT FK_DimEmployee_405 FOREIGN KEY ( SalesTerritoryKey ) REFERENCES EDW.DimSalesTerritory ( SalesTerritoryKey )
);

COMMENT ON TABLE EDW.DimEmployee IS 'This table holds all Employee Information';


-- ************************************** EDW.ChildDemo
CREATE TABLE EDW.ChildDemo
(
 ScenarioKey decimal(38,0) NOT NULL,
 CreatedBy   varchar(50) NOT NULL,
 CreatedDate timestamp NOT NULL,
 UpdatedDate timestamp NOT NULL,
 UpdatedBy   varchar(50) NOT NULL,
 TESTCOLUMN  decimal(38,0) NOT NULL,
 etl_id      timestamp NOT NULL, -- From template: "Template_w_etl"

 CONSTRAINT PK_664 PRIMARY KEY ( ScenarioKey ),
 CONSTRAINT FK_661 FOREIGN KEY ( ScenarioKey ) REFERENCES EDW.DimScenario ( ScenarioKey )
);

COMMENT ON COLUMN EDW.ChildDemo.ScenarioKey IS 'Scenario Identifier';


-- ************************************** EDW.child_DimProduct
CREATE TABLE EDW.child_DimProduct
(
 ProductKey            decimal(38,0) NOT NULL,
 WeightUnitMeasureCode varchar(3),
 FrenchProductName     varchar(50),
 StandardCost          decimal(38,0),
 FinishedGoodsFlag     decimal(38,0) NOT NULL,
 ReorderPoint          decimal(38,0),

 CONSTRAINT FK_36 FOREIGN KEY ( ProductKey ) REFERENCES EDW.DimProduct ( ProductKey )
)
BACKUP NO;


-- ************************************** EDW.NewFactCurrencyRate
CREATE TABLE EDW.NewFactCurrencyRate
(
 AverageRate  float,
 CurrencyID   varchar(3),
 CurrencyDate date,
 EndOfDayRate float,
 CurrencyKey  decimal(38,0),
 DateKey      decimal(38,0),
 etl_id       timestamp NOT NULL, -- From template: "Template_w_etl"

 CONSTRAINT FK_NewFactCurrencyRate_469 FOREIGN KEY ( CurrencyKey ) REFERENCES EDW.DimCurrency ( CurrencyKey ),
 CONSTRAINT FK_NewFactCurrencyRate_471 FOREIGN KEY ( DateKey ) REFERENCES EDW.DimDate ( DateKey )
);


-- ************************************** EDW.FactSalesQuota
CREATE TABLE EDW.FactSalesQuota
(
 SalesQuotaKey    decimal(38,0) IDENTITY ( 1, 1 ),
 EmployeeKey      decimal(38,0) NOT NULL,
 DateKey          decimal(38,0) NOT NULL,
 CalendarYear     decimal(38,0) NOT NULL,
 CalendarQuarter  decimal(38,0) NOT NULL,
 SalesAmountQuota decimal(38,0) NOT NULL,
 etl_id           timestamp NOT NULL, -- From template: "Template_w_etl"

 CONSTRAINT FK_FactSalesQuota_463 FOREIGN KEY ( DateKey ) REFERENCES EDW.DimDate ( DateKey )
);


-- ************************************** EDW.DimReseller
CREATE TABLE EDW.DimReseller
(
 ResellerKey          decimal(38,0) IDENTITY ( 1, 1 ),
 GeographyKey         decimal(38,0),
 ResellerAlternateKey varchar(15),
 Phone                varchar(25),
 BusinessType         varchar(20) NOT NULL,
 ResellerName         varchar(50) NOT NULL,
 NumberEmployees      decimal(38,0),
 OrderFrequency       varchar(1),
 OrderMonth           decimal(38,0),
 FirstOrderYear       decimal(38,0),
 LastOrderYear        decimal(38,0),
 ProductLine          varchar(50),
 AddressLine1         varchar(60),
 AddressLine2         varchar(60),
 AnnualSales          decimal(38,0),
 BankName             varchar(50),
 MinPaymentType       decimal(38,0),
 MinPaymentAmount     decimal(38,0),
 AnnualRevenue        decimal(38,0),
 YearOpened           decimal(38,0),
 etl_id               timestamp NOT NULL, -- From template: "Template_w_etl"

 CONSTRAINT PK_DimReseller PRIMARY KEY ( ResellerKey ),
 CONSTRAINT FK_DimReseller_411 FOREIGN KEY ( GeographyKey ) REFERENCES EDW.DimGeography ( GeographyKey )
);


-- ************************************** EDW.DimOrganization
CREATE TABLE EDW.DimOrganization
(
 OrganizationKey       decimal(38,0) IDENTITY ( 1, 1 ),
 ParentOrganizationKey decimal(38,0),
 PercentageOfOwnership varchar(16),
 OrganizationName      varchar(50),
 CurrencyKey           decimal(38,0),
 etl_id                timestamp NOT NULL, -- From template: "Template_w_etl"

 CONSTRAINT PK_DimOrganization PRIMARY KEY ( OrganizationKey )
);

COMMENT ON TABLE EDW.DimOrganization IS 'Dimension for Organizational Data';


-- ************************************** EDW.DimCustomer
CREATE TABLE EDW.DimCustomer
(
 CustomerKey          decimal(38,0) IDENTITY ( 1, 1 ),
 GeographyKey         decimal(38,0),
 CustomerAlternateKey varchar(15) NOT NULL,
 Title                varchar(8),
 FirstName            varchar(50),
 MiddleName           varchar(50),
 LastName             varchar(50),
 NameStyle            varchar(5),
 BirthDate            date,
 MaritalStatus        varchar(1),
 Suffix               varchar(10),
 Gender               varchar(1),
 EmailAddress         varchar(50),
 YearlyIncome         decimal(38,0),
 TotalChildren        decimal(38,0),
 NumberChildrenAtHome decimal(38,0),
 EnglishEducation     varchar(40),
 SpanishEducation     varchar(40),
 FrenchEducation      varchar(40),
 EnglishOccupation    varchar(100),
 SpanishOccupation    varchar(100),
 FrenchOccupation     varchar(100),
 HouseOwnerFlag       varchar(1),
 NumberCarsOwned      decimal(38,0),
 AddressLine          varchar(120),
 AddressLine2         varchar(120),
 Phone                varchar(20),
 DateFirstPurchase    date,
 CommuteDistance      varchar(15),
 etl_id               timestamp NOT NULL, -- From template: "Template_w_etl"

 CONSTRAINT PK_DimCustomer PRIMARY KEY ( CustomerKey ),
 CONSTRAINT FK_DimCustomer_401 FOREIGN KEY ( GeographyKey ) REFERENCES EDW.DimGeography ( GeographyKey )
);

COMMENT ON TABLE EDW.DimCustomer IS 'Dimension for Customer Data';

COMMENT ON COLUMN EDW.DimCustomer.CustomerKey IS 'Customer Identifier';
COMMENT ON COLUMN EDW.DimCustomer.GeographyKey IS 'Geographic informatio';
COMMENT ON COLUMN EDW.DimCustomer.CustomerAlternateKey IS 'Alternate Key';
COMMENT ON COLUMN EDW.DimCustomer.Title IS 'Title of the Customer';


-- ************************************** EDW.FactSurveyResponse
CREATE TABLE EDW.FactSurveyResponse
(
 SurveyResponseKey             decimal(38,0) IDENTITY ( 1, 1 ),
 DateKey                       decimal(38,0) NOT NULL,
 CustomerKey                   decimal(38,0) NOT NULL,
 ProductCategoryKey            decimal(38,0) NOT NULL,
 EnglishProductCategoryName    varchar(50) NOT NULL,
 ProductSubcategoryKey         decimal(38,0) NOT NULL,
 EnglishProductSubcategoryName varchar(50) NOT NULL,
 etl_id                        timestamp NOT NULL, -- From template: "Template_w_etl"

 CONSTRAINT FK_FactSurveyResponse_465 FOREIGN KEY ( DateKey ) REFERENCES EDW.DimDate ( DateKey ),
 CONSTRAINT FK_FactSurveyResponse_467 FOREIGN KEY ( ProductCategoryKey ) REFERENCES EDW.DimProductCategory ( ProductCategoryKey )
);


-- ************************************** EDW.FactResellerSales
CREATE TABLE EDW.FactResellerSales
(
 ProductKey            decimal(38,0) NOT NULL,
 OrderDateKey          decimal(38,0) NOT NULL,
 DueDateKey            decimal(38,0) NOT NULL,
 ShipDateKey           decimal(38,0) NOT NULL,
 ResellerKey           decimal(38,0) NOT NULL,
 EmployeeKey           decimal(38,0) NOT NULL,
 PromotionKey          decimal(38,0) NOT NULL,
 CurrencyKey           decimal(38,0) NOT NULL,
 SalesTerritoryKey     decimal(38,0) NOT NULL,
 SalesOrderNumber      varchar(20) NOT NULL,
 SalesOrderLineNumber  decimal(38,0) NOT NULL,
 RevisionNumber        decimal(38,0),
 OrderQuantity         decimal(38,0),
 UnitPrice             decimal(38,0),
 ExtendedAmount        decimal(38,0),
 UnitPriceDiscountPct  float,
 DiscountAmount        float,
 ProductStandardCost   decimal(38,0),
 TotalProductCost      decimal(38,0),
 SalesAmount           decimal(38,0),
 TaxAmt                decimal(38,0),
 Freight               decimal(38,0),
 CarrierTrackingNumber varchar(25),
 CustomerPONumber      varchar(25),
 etl_id                timestamp NOT NULL, -- From template: "Template_w_etl"

 CONSTRAINT FK_FactResellerSales_445 FOREIGN KEY ( ProductKey ) REFERENCES EDW.DimProduct ( ProductKey ),
 CONSTRAINT FK_FactResellerSales_447 FOREIGN KEY ( ResellerKey ) REFERENCES EDW.DimReseller ( ResellerKey ),
 CONSTRAINT FK_FactResellerSales_449 FOREIGN KEY ( EmployeeKey ) REFERENCES EDW.DimEmployee ( EmployeeKey ),
 CONSTRAINT FK_FactResellerSales_451 FOREIGN KEY ( PromotionKey ) REFERENCES EDW.DimPromotion ( PromotionKey ),
 CONSTRAINT FK_FactResellerSales_453 FOREIGN KEY ( CurrencyKey ) REFERENCES EDW.DimCurrency ( CurrencyKey ),
 CONSTRAINT FK_FactResellerSales_455 FOREIGN KEY ( SalesTerritoryKey ) REFERENCES EDW.DimSalesTerritory ( SalesTerritoryKey ),
 CONSTRAINT FK_FactResellerSales_457 FOREIGN KEY ( OrderDateKey ) REFERENCES EDW.DimDate ( DateKey ),
 CONSTRAINT FK_FactResellerSales_459 FOREIGN KEY ( DueDateKey ) REFERENCES EDW.DimDate ( DateKey ),
 CONSTRAINT FK_FactResellerSales_461 FOREIGN KEY ( ShipDateKey ) REFERENCES EDW.DimDate ( DateKey )
);

COMMENT ON TABLE EDW.FactResellerSales IS 'Fact data of Reseller Sales';


-- ************************************** EDW.FactInternetSales
CREATE TABLE EDW.FactInternetSales
(
 ProductKey            decimal(38,0) NOT NULL,
 OrderDateKey          decimal(38,0) NOT NULL,
 DueDateKey            decimal(38,0) NOT NULL,
 ShipDateKey           decimal(38,0) NOT NULL,
 CustomerKey           decimal(38,0) NOT NULL,
 PromotionKey          decimal(38,0) NOT NULL,
 CurrencyKey           decimal(38,0) NOT NULL,
 SalesTerritoryKey     decimal(38,0) NOT NULL,
 SalesOrderNumber      varchar(20) NOT NULL,
 SalesOrderLineNumber  decimal(38,0) NOT NULL,
 RevisionNumber        decimal(38,0) NOT NULL,
 OrderQuantity         decimal(38,0) NOT NULL,
 UnitPrice             decimal(38,0) NOT NULL,
 ExtendedAmount        decimal(38,0) NOT NULL,
 UnitPriceDiscountPct  float NOT NULL,
 DiscountAmount        float NOT NULL,
 ProductStandardCost   decimal(38,0) NOT NULL,
 TotalProductCost      decimal(38,0) NOT NULL,
 SalesAmount           decimal(38,0) NOT NULL,
 TaxAmt                decimal(38,0) NOT NULL,
 Freight               decimal(38,0) NOT NULL,
 CarrierTrackingNumber varchar(25),
 CustomerPONumber      varchar(25),
 etl_id                timestamp NOT NULL, -- From template: "Template_w_etl"

 CONSTRAINT FK_FactInternetSales_427 FOREIGN KEY ( ProductKey ) REFERENCES EDW.DimProduct ( ProductKey ),
 CONSTRAINT FK_FactInternetSales_429 FOREIGN KEY ( CustomerKey ) REFERENCES EDW.DimCustomer ( CustomerKey ),
 CONSTRAINT FK_FactInternetSales_431 FOREIGN KEY ( PromotionKey ) REFERENCES EDW.DimPromotion ( PromotionKey ),
 CONSTRAINT FK_FactInternetSales_433 FOREIGN KEY ( CurrencyKey ) REFERENCES EDW.DimCurrency ( CurrencyKey ),
 CONSTRAINT FK_FactInternetSales_435 FOREIGN KEY ( SalesTerritoryKey ) REFERENCES EDW.DimSalesTerritory ( SalesTerritoryKey ),
 CONSTRAINT FK_FactInternetSales_437 FOREIGN KEY ( OrderDateKey ) REFERENCES EDW.DimDate ( DateKey ),
 CONSTRAINT FK_FactInternetSales_439 FOREIGN KEY ( DueDateKey ) REFERENCES EDW.DimDate ( DateKey ),
 CONSTRAINT FK_FactInternetSales_441 FOREIGN KEY ( ShipDateKey ) REFERENCES EDW.DimDate ( DateKey )
);

COMMENT ON TABLE EDW.FactInternetSales IS 'Fact table to hold Currency Data';


-- ************************************** EDW.FactFinance
CREATE TABLE EDW.FactFinance
(
 FinanceKey         decimal(38,0) IDENTITY ( 1, 1 ),
 DateKey            decimal(38,0) NOT NULL,
 OrganizationKey    decimal(38,0) NOT NULL,
 DepartmentGroupKey decimal(38,0) NOT NULL,
 ScenarioKey        decimal(38,0) NOT NULL,
 AccountKey         decimal(38,0) NOT NULL,
 Amount             float NOT NULL,
 etl_id             timestamp NOT NULL, -- From template: "Template_w_etl"

 CONSTRAINT FK_FactFinance_417 FOREIGN KEY ( DateKey ) REFERENCES EDW.DimDate ( DateKey ),
 CONSTRAINT FK_FactFinance_419 FOREIGN KEY ( OrganizationKey ) REFERENCES EDW.DimOrganization ( OrganizationKey ),
 CONSTRAINT FK_FactFinance_421 FOREIGN KEY ( DepartmentGroupKey ) REFERENCES EDW.DimDepartmentGroup ( DepartmentGroupKey ),
 CONSTRAINT FK_FactFinance_423 FOREIGN KEY ( ScenarioKey ) REFERENCES EDW.DimScenario ( ScenarioKey ),
 CONSTRAINT FK_FactFinance_425 FOREIGN KEY ( AccountKey ) REFERENCES EDW.DimAccount ( AccountKey )
);

COMMENT ON TABLE EDW.FactFinance IS 'Facts for Finance';


