-- ************************* SqlDBM: Databricks *************************
-- ***** Generated by SqlDBM: Databricks Demo by hzlsener@gmail.com *****




-- ************************************** mySchema.sub_partsupp
CREATE TABLE mySchema.sub_partsupp
(
 sub_parsupp_key bigint NOT NULL,
 sub_availqty    int,
 sub_supplycost  decimal(18, 2)
);



-- ************************************** mySchema.region
CREATE TABLE mySchema.region
(
 regionkey bigint,
 name      string,
 comment   string
)
USING DELTA;



-- ************************************** mySchema.partsupp
CREATE TABLE mySchema.partsupp
(
 partkey    bigint NOT NULL,
 suppkey    bigint NOT NULL,
 availqty   int,
 supplycost decimal(18, 2),
 comment    string,
 CONSTRAINT PK_PK_2_partsupp PRIMARY KEY (partkey, suppkey)
)
USING DELTA;



-- ************************************** mySchema.part
CREATE TABLE mySchema.part
(
 partkey     bigint,
 name        string,
 mfgr        string,
 brand       string,
 type        string,
 size        int,
 container   string,
 retailprice decimal(18, 2),
 comment     string
)
USING DELTA;



-- ************************************** mySchema.nation
CREATE TABLE mySchema.nation
(
 nationkey bigint NOT NULL CONSTRAINT PK_3_nation PRIMARY KEY,
 name      string,
 regionkey bigint,
 comment   string
)
USING DELTA;



-- ************************************** mySchema.supplier
CREATE TABLE mySchema.supplier
(
 suppkey   bigint NOT NULL,
 nationkey bigint NOT NULL CONSTRAINT FK_nation REFERENCES mySchema.nation,
 name      string,
 address   string,
 phone     string,
 acctbal   decimal(18, 2),
 comment   string,
 CONSTRAINT PK_PK_2_supplier PRIMARY KEY (suppkey, nationkey)
)
USING DELTA;



-- ************************************** mySchema.customer
CREATE TABLE mySchema.customer
(
 custkey      bigint NOT NULL COMMENT 'Customer identifier' CONSTRAINT PK_PK_2_customer PRIMARY KEY,
 name         string COMMENT 'Customer name',
 address      string COMMENT 'Billing address',
 nationkey    bigint COMMENT 'Customer nationality code',
 phone        string COMMENT 'Phone number of the customer',
 acctbal      decimal(18, 2),
 active_years bigint COMMENT 'Since when the customer is registered',
 mktsegment   string COMMENT 'Segment of the client',
 comment      string COMMENT 'Any additional comment about the customer'
)
USING DELTA;



-- ************************************** vip_customer
CREATE TABLE vip_customer
(
 custkey    bigint NOT NULL COMMENT 'Customer identifier',
 vip_points integer NOT NULL
);



-- ************************************** mySchema.orders
CREATE TABLE mySchema.orders
(
 orderkey      bigint NOT NULL,
 custkey       bigint NOT NULL CONSTRAINT FK_customer REFERENCES mySchema.customer,
 orderstatus   string,
 totalprice    decimal(18, 2),
 orderdate     date,
 orderpriority string,
 clerk         string,
 shippriority  int,
 comment       string,
 CONSTRAINT PK_3_orders PRIMARY KEY (orderkey, custkey)
)
USING DELTA;



-- ************************************** mySchema.lineitem
CREATE TABLE mySchema.lineitem
(
 linenumber    int NOT NULL CONSTRAINT PK_PK_2_lineitem PRIMARY KEY,
 partkey       bigint,
 suppkey       bigint NOT NULL,
 nationkey     bigint NOT NULL,
 quantity      decimal(18, 2),
 extendedprice decimal(18, 2),
 discount      decimal(18, 2),
 tax           decimal(18, 2),
 returnflag    string,
 linestatus    string,
 shipdate      date,
 commitdate    date,
 receiptdate   date,
 shipinstruct  string,
 shipmode      string,
 comment       string,
 CONSTRAINT FK_supplier FOREIGN KEY (suppkey, nationkey) REFERENCES mySchema.supplier (suppkey, nationkey)
)
USING DELTA;



-- ************************************** mySchema.order_lineitem
CREATE TABLE mySchema.order_lineitem
(
 orderkey   bigint NOT NULL,
 custkey    bigint NOT NULL,
 linenumber int NOT NULL CONSTRAINT FK_lineitem REFERENCES mySchema.lineitem,
 CONSTRAINT PK_1_order_lineitem PRIMARY KEY (orderkey, custkey, linenumber),
 CONSTRAINT FK_orders_1 FOREIGN KEY (orderkey, custkey) REFERENCES mySchema.orders (orderkey, custkey)
);

-- ************************************** mySchema.nation_region
-- Create a temporary view denormalizing nation with regionCREATE TEMPORARY VIEW myDb.mySchema.nation_region
    AS SELECT na.nationkey , na.name , na.regionkey, re.name
         FROM myDb.mySchema.nation AS na 
         INNER JOIN myDb.mySchema.region AS re 
            ON na.regionkey = re.regionkey;

-- ************************************** mySchema.legacy_customerCREATE VIEW myDb.mySchema.legacy_customer
    (custkey COMMENT 'Unique identification number', 
	 name
	)
    COMMENT 'View for legacy customers with over 5 years of loyalty'
    AS SELECT custkey, name
         FROM myDb.mySchema.customer
        WHERE active_years >= 5;

