-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Awesome Project, v133 by hazal.sener@sqldbm.com *


-- ************************************** EDW.cost_center
CREATE TAG EDW.cost_center ALLOWED_VALUES 'val_1', 'val_2'
 COMMENT = 'cost center tag';
