-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Awesome Project, v133 by hazal.sener@sqldbm.com *


-- ************************************** HOTELBNB.Tag_2
CREATE TAG HOTELBNB.Tag_2 ALLOWED_VALUES 'val_3'
 COMMENT = 'demo';
