-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: AdWorks project, v952 by serge@sqldbm.com ***


-- ************************************** Tag1
CREATE TAG IF NOT EXISTS Tag1;
