-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: Awesome Project by daniel.jimenez+team@sqldbm.com *


-- ************************************** TAG_SCHEMA.Medallion
CREATE TAG TAG_SCHEMA.Medallion ALLOWED_VALUES 'Gold', 'Silver', 'Bronze';
