-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: Awesome Project by daniel.jimenez+team@sqldbm.com *


-- ************************************** TAG_SCHEMA.Issues
CREATE TAG TAG_SCHEMA.Issues;
