-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: AdWorks project, v952 by serge@sqldbm.com ***


CREATE OR REPLACE FILE FORMAT "ADVENTUREWORKSDW.EDW.FILEFORMAT_431"
 TYPE = JSON;
