-- ***************************** SqlDBM: Snowflake ****************************
-- * Generated by SqlDBM: AdWorks project, v1032 vs v1028 by serge@sqldbm.com *

DROP TABLE IF EXISTS Table2514;

DROP TABLE IF EXISTS dim_Account_Type_1;

CREATE TABLE IF NOT EXISTS MyLogicalName
(

);