-- *********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: Awesome Project, v124 vs v111 by daniel.jimenez+team@sqldbm.com *

DROP TABLE sqldbm_new_table;

DROP TABLE sqldbm_role_name_applied;

ALTER TABLE EDW.sqldbm_DimScenario
    ADD COLUMN test_col varchar NOT NULL;

ALTER TABLE EDW.sqldbm_ChildDemo
    DROP COLUMN SampleColumn2;

CREATE TABLE SFLK_DATA.sqldbm_role_name_applied
(
 GeographyKey_2 number(38,0) NOT NULL,
 ETL_ID         timestamp NOT NULL COMMENT 'Table load date', 
 ETL_TIMESTAMP  timestamp_ntz NOT NULL COMMENT 'Table load date TIME', 

 CONSTRAINT PK_1_sqldbm_role_name_applied PRIMARY KEY ( GeographyKey_2 ),
 CONSTRAINT FK_sqldbm_DimGeography_sqldbm_role_name_applied FOREIGN KEY ( GeographyKey_2 ) REFERENCES EDW.sqldbm_DimGeography ( GeographyKey )
);

CREATE TABLE SFLK_DATA.sqldbm_template
(
 ScenarioKey   number(38,0) NOT NULL COMMENT 'Scenario Identifier',
 ETL_ID        timestamp NOT NULL COMMENT 'Table load date', 
 ETL_TIMESTAMP timestamp_ntz NOT NULL COMMENT 'Table load date TIME', 

 CONSTRAINT PK_1_sqldbm_template PRIMARY KEY ( ScenarioKey )
);

CREATE TABLE SFLK_DATA.sqldbm_DimReseller_child
(
 ResellerKey          number(38,0) NOT NULL COMMENT 'Reseller identifier',
 ResellerAlternateKey varchar(15) COMMENT 'Reseller alternate key',
 BusinessType         varchar(20) NOT NULL,
 ResellerName         varchar(50) NOT NULL,
 NumberEmployees      number(38,0),
 ETL_ID               timestamp NOT NULL COMMENT 'Table load date', 
 ETL_TIMESTAMP        timestamp_ntz NOT NULL COMMENT 'Table load date TIME', 

 CONSTRAINT PK_1_sqldbm_DimReseller_child PRIMARY KEY ( ResellerKey ),
 CONSTRAINT FK_sqldbm_DimReseller_sqldbm_DimReseller_child FOREIGN KEY ( ResellerKey ) REFERENCES EDW.sqldbm_DimReseller ( ResellerKey )
);

CREATE TABLE sqldbm_31
(
 ResellerKey   number(38,0) NOT NULL COMMENT 'Reseller identifier',
 ETL_ID        timestamp NOT NULL COMMENT 'Table load date', 
 ETL_TIMESTAMP timestamp_ntz NOT NULL COMMENT 'Table load date TIME', 

 CONSTRAINT PK_2_sqldbm_31 PRIMARY KEY ( ResellerKey ),
 CONSTRAINT FK_sqldbm_DimReseller_child_sqldbm_31 FOREIGN KEY ( ResellerKey ) REFERENCES SFLK_DATA.sqldbm_DimReseller_child ( ResellerKey )
);