-- ******************************* SqlDBM: Snowflake ******************************
-- * Generated by SqlDBM: Awesome Project, v124 vs v123 by hazal.sener@sqldbm.com *

CREATE TABLE "sqldbm_31"
(
 "ResellerKey"   number(38,0) NOT NULL COMMENT 'Reseller identifier',
 "ETL_ID"        timestamp NOT NULL COMMENT 'Table load date', 
 "ETL_TIMESTAMP" timestamp_ntz NOT NULL COMMENT 'Table load date TIME', 

 CONSTRAINT "PK_2_sqldbm_31" PRIMARY KEY ( "ResellerKey" ),
 CONSTRAINT "FK_sqldbm_DimReseller_child_sqldbm_31" FOREIGN KEY ( "ResellerKey" ) REFERENCES "SFLK_DATA"."sqldbm_DimReseller_child" ( "ResellerKey" )
);