-- *********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: Awesome Project, v130 vs v111 by daniel.jimenez+team@sqldbm.com *

DROP TABLE sqldbm_new_table;

DROP TABLE sqldbm_role_name_applied;

ALTER TABLE EDW.sqldbm_DimAccount
    DROP COLUMN AccountType;

ALTER TABLE EDW.sqldbm_DimAccount
    DROP COLUMN CustomMembers;

ALTER TABLE EDW.sqldbm_DimAccount
    DROP COLUMN ValueType;

ALTER TABLE EDW.sqldbm_DimScenario
    ADD COLUMN test_col varchar NOT NULL;

ALTER TABLE EDW.sqldbm_ChildDemo
    DROP COLUMN SampleColumn2;

CREATE TABLE Tabla_Ejemplo
(
 "Columna Ejemplo"  NOT NULL,
 ETL_ID          timestamp NOT NULL COMMENT 'Table load date', 
 ETL_TIMESTAMP   timestamp_ntz NOT NULL COMMENT 'Table load date TIME', 

 CONSTRAINT PK_1_Tabla_Ejemplo PRIMARY KEY ( "Columna Ejemplo" )
);

CREATE TABLE SampleTable
(
 ETL_ID        timestamp NOT NULL COMMENT 'Table load date', 
 ETL_TIMESTAMP timestamp_ntz NOT NULL COMMENT 'Table load date TIME', 
 SampleColumn  varchar(50) NOT NULL
);

CREATE TABLE Danny_Table
(
 ETL_ID        timestamp NOT NULL COMMENT 'Table load date', 
 ETL_TIMESTAMP timestamp_ntz NOT NULL COMMENT 'Table load date TIME' 

);

CREATE TABLE SFLK_DATA.sqldbm_role_name_applied
(
 GeographyKey_2 number(38,0) NOT NULL,
 ETL_ID         timestamp NOT NULL COMMENT 'Table load date', 
 ETL_TIMESTAMP  timestamp_ntz NOT NULL COMMENT 'Table load date TIME', 

 CONSTRAINT PK_1_sqldbm_role_name_applied PRIMARY KEY ( GeographyKey_2 ),
 CONSTRAINT FK_sqldbm_DimGeography_sqldbm_role_name_applied FOREIGN KEY ( GeographyKey_2 ) REFERENCES EDW.sqldbm_DimGeography ( GeographyKey )
);

CREATE TABLE Sample_Table
(
 "Sample Column"  NOT NULL,
 ETL_ID        timestamp NOT NULL COMMENT 'Table load date', 
 ETL_TIMESTAMP timestamp_ntz NOT NULL COMMENT 'Table load date TIME', 

 CONSTRAINT PK_1_Sample_Table PRIMARY KEY ( "Sample Column" )
);

CREATE TABLE EDW.child_DimAccount
(
 AccountKey    number(38,0) NOT NULL COMMENT 'Unique Identifier of the Account data from Salesforce',
 ETL_ID        timestamp NOT NULL COMMENT 'Table load date', 
 ETL_TIMESTAMP timestamp_ntz NOT NULL COMMENT 'Table load date TIME', 
 AccountType   varchar(50) COMMENT 'The type of the Account',
 CustomMembers varchar(300) COMMENT 'Member of the account',
 ValueType     varchar(50) COMMENT 'The value of the Account',

 CONSTRAINT FK_sqldbm_DimAccount_child_DimAccount FOREIGN KEY ( AccountKey ) REFERENCES EDW.sqldbm_DimAccount ( AccountKey )
);

CREATE TABLE SFLK_DATA.sqldbm_template
(
 ScenarioKey   number(38,0) NOT NULL COMMENT 'Scenario Identifier',
 ETL_ID        timestamp NOT NULL COMMENT 'Table load date', 
 ETL_TIMESTAMP timestamp_ntz NOT NULL COMMENT 'Table load date TIME', 

 CONSTRAINT PK_1_sqldbm_template PRIMARY KEY ( ScenarioKey )
);

CREATE TABLE SFLK_DATA.sqldbm_DimReseller_child
(
 ResellerKey          number(38,0) NOT NULL COMMENT 'Reseller identifier',
 ResellerAlternateKey varchar(15) COMMENT 'Reseller alternate key',
 BusinessType         varchar(20) NOT NULL,
 ResellerName         varchar(50) NOT NULL,
 NumberEmployees      number(38,0),
 ETL_ID               timestamp NOT NULL COMMENT 'Table load date', 
 ETL_TIMESTAMP        timestamp_ntz NOT NULL COMMENT 'Table load date TIME', 

 CONSTRAINT PK_1_sqldbm_DimReseller_child PRIMARY KEY ( ResellerKey ),
 CONSTRAINT FK_sqldbm_DimReseller_sqldbm_DimReseller_child FOREIGN KEY ( ResellerKey ) REFERENCES EDW.sqldbm_DimReseller ( ResellerKey )
);

CREATE TABLE sqldbm_31
(
 ResellerKey   number(38,0) NOT NULL COMMENT 'Reseller identifier',
 ETL_ID        timestamp NOT NULL COMMENT 'Table load date', 
 ETL_TIMESTAMP timestamp_ntz NOT NULL COMMENT 'Table load date TIME', 

 CONSTRAINT PK_2_sqldbm_31 PRIMARY KEY ( ResellerKey ),
 CONSTRAINT FK_sqldbm_DimReseller_child_sqldbm_31 FOREIGN KEY ( ResellerKey ) REFERENCES SFLK_DATA.sqldbm_DimReseller_child ( ResellerKey )
);