-- ****************************** SqlDBM: Snowflake *****************************
-- * Generated by SqlDBM: Awesome Project, v72 vs v53 by hazal.sener@sqldbm.com *

DROP TABLE HOTELBNB.sqldbm_DESTINATIONS;

ALTER TABLE EDW.sqldbm_DimEmployee
    DROP COLUMN ETL_ID;

ALTER TABLE EDW.sqldbm_DimEmployee
    DROP COLUMN ETL_TIMESTAMP;

ALTER TABLE EDW.sqldbm_DimSalesTerritory
    DROP COLUMN ETL_ID;

ALTER TABLE EDW.sqldbm_DimSalesTerritory
    DROP COLUMN ETL_TIMESTAMP;

ALTER TABLE EDW.sqldbm_FactProductInventory
    DROP COLUMN ETL_ID;

ALTER TABLE EDW.sqldbm_FactProductInventory
    DROP COLUMN ETL_TIMESTAMP;

ALTER TABLE EDW.sqldbm_NewFactCurrencyRate
    DROP COLUMN ETL_ID;

ALTER TABLE EDW.sqldbm_NewFactCurrencyRate
    DROP COLUMN ETL_TIMESTAMP;

ALTER TABLE EDW.sqldbm_FactCurrencyRate
    DROP COLUMN ETL_ID;

ALTER TABLE EDW.sqldbm_FactCurrencyRate
    DROP COLUMN ETL_TIMESTAMP;

ALTER TABLE EDW.sqldbm_FactSalesQuota
    DROP COLUMN ETL_ID;

ALTER TABLE EDW.sqldbm_FactSalesQuota
    DROP COLUMN ETL_TIMESTAMP;

ALTER TABLE EDW.sqldbm_FactSurveyResponse
    DROP COLUMN ETL_ID;

ALTER TABLE EDW.sqldbm_FactSurveyResponse
    DROP COLUMN ETL_TIMESTAMP;

ALTER TABLE EDW.sqldbm_DimReseller
    DROP COLUMN ETL_ID;

ALTER TABLE EDW.sqldbm_DimReseller
    DROP COLUMN ETL_TIMESTAMP;

ALTER TABLE EDW.sqldbm_ChildDemo
    DROP COLUMN ETL_ID;

ALTER TABLE EDW.sqldbm_ChildDemo
    DROP COLUMN ETL_TIMESTAMP;

ALTER TABLE EDW.sqldbm_DimGeography
    DROP COLUMN ETL_ID;

ALTER TABLE EDW.sqldbm_DimGeography
    DROP COLUMN ETL_TIMESTAMP;

ALTER TABLE EDW.sqldbm_table_w_error
    SET COMMENT = 'The table with an error. Data type is forgotten';

ALTER TABLE EDW.sqldbm_table_w_error
    DROP COLUMN ETL_ID;

ALTER TABLE EDW.sqldbm_table_w_error
    DROP COLUMN ETL_TIMESTAMP;

ALTER TABLE EDW.sqldbm_table_w_error
    ADD COLUMN new_column number(38,0) NOT NULL;

ALTER TABLE EDW.sqldbm_DimCurrency
    DROP COLUMN ETL_ID;

ALTER TABLE EDW.sqldbm_DimCurrency
    DROP COLUMN ETL_TIMESTAMP;

ALTER TABLE EDW.sqldbm_DimProductCategory
    DROP COLUMN ETL_ID;

ALTER TABLE EDW.sqldbm_DimProductCategory
    DROP COLUMN ETL_TIMESTAMP;

ALTER TABLE EDW.sqldbm_DimPromotion
    DROP COLUMN ETL_ID;

ALTER TABLE EDW.sqldbm_DimPromotion
    DROP COLUMN ETL_TIMESTAMP;

ALTER TABLE EDW.sqldbm_DimCustomer
    DROP COLUMN ETL_ID;

ALTER TABLE EDW.sqldbm_DimCustomer
    DROP COLUMN ETL_TIMESTAMP;

ALTER TABLE sqldbm_sold
    DROP COLUMN ETL_ID;

ALTER TABLE sqldbm_sold
    DROP COLUMN ETL_TIMESTAMP;

ALTER TABLE EDW.sqldbm_FactResellerSales
    DROP COLUMN ETL_ID;

ALTER TABLE EDW.sqldbm_FactResellerSales
    DROP COLUMN ETL_TIMESTAMP;

ALTER TABLE EDW.sqldbm_FactInternetSales
    DROP COLUMN ETL_ID;

ALTER TABLE EDW.sqldbm_FactInternetSales
    DROP COLUMN ETL_TIMESTAMP;

ALTER TABLE EDW.sqldbm_DimProductSubcategory
    DROP COLUMN ETL_ID;

ALTER TABLE EDW.sqldbm_DimProductSubcategory
    DROP COLUMN ETL_TIMESTAMP;

ALTER TABLE EDW.sqldbm_DimProduct
    DROP COLUMN Color;

ALTER TABLE EDW.sqldbm_DimProduct
    DROP COLUMN ETL_ID;

ALTER TABLE EDW.sqldbm_DimProduct
    DROP COLUMN ETL_TIMESTAMP;

ALTER TABLE EDW.sqldbm_DimDepartmentGroup
    DROP COLUMN ETL_ID;

ALTER TABLE EDW.sqldbm_DimDepartmentGroup
    DROP COLUMN ETL_TIMESTAMP;

ALTER TABLE EDW.sqldbm_DimOrganization
    DROP COLUMN ETL_ID;

ALTER TABLE EDW.sqldbm_DimOrganization
    DROP COLUMN ETL_TIMESTAMP;

ALTER TABLE EDW.sqldbm_DimScenario
    DROP COLUMN ETL_ID;

ALTER TABLE EDW.sqldbm_DimScenario
    DROP COLUMN ETL_TIMESTAMP;

ALTER TABLE EDW.sqldbm_FactFinance
    DROP COLUMN ETL_ID;

ALTER TABLE EDW.sqldbm_FactFinance
    DROP COLUMN ETL_TIMESTAMP;

ALTER TABLE EDW.sqldbm_DimAccount
    DROP COLUMN Operator;

ALTER TABLE EDW.sqldbm_DimAccount
    DROP COLUMN ETL_ID;

ALTER TABLE EDW.sqldbm_DimAccount
    DROP COLUMN ETL_TIMESTAMP;

ALTER TABLE EDW.sqldbm_DimDate
    DROP COLUMN ETL_ID;

ALTER TABLE EDW.sqldbm_DimDate
    DROP COLUMN ETL_TIMESTAMP;