-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** EDW.sqldbm_DimCurrency
CREATE TABLE EDW.sqldbm_DimCurrency
(
 CurrencyKey          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Currency Identifier',
 CurrencyAlternateKey varchar(3) NOT NULL COMMENT 'Alternate Currency Identifier',
 ProductKey           number(38,0) NOT NULL COMMENT 'Product identifier',
 CurrencyName         varchar(50) NOT NULL COMMENT 'Name of the Currency',

 CONSTRAINT PK_DimCurrency_sqldbm_DimCurrency PRIMARY KEY ( CurrencyKey ),
 CONSTRAINT FK_sqldbm_DimProduct_sqldbm_DimCurrency FOREIGN KEY ( ProductKey ) REFERENCES EDW.sqldbm_DimProduct ( ProductKey )
)
COMMENT = 'Dimension for Currency Data';
