-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** EDW.sqldbm_DimOrganization
CREATE TABLE EDW.sqldbm_DimOrganization
(
 OrganizationKey       number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Organizarion identifier',
 ParentOrganizationKey number(38,0) COMMENT 'Organizarion identifier for the parent relationship',
 PercentageOfOwnership varchar(16) COMMENT 'Ownership percentage of the organization',
 OrganizationName      varchar(50),
 CurrencyKey           number(38,0) COMMENT 'Currency Identifier',

 CONSTRAINT PK_DimOrganization_sqldbm_DimOrganization PRIMARY KEY ( OrganizationKey )
)
COMMENT = 'Dimension for Organizational Data';
