-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** sqldbm_sold
CREATE TABLE sqldbm_sold
(
 ProductKey number(38,0) NOT NULL COMMENT 'Product identifier',

 CONSTRAINT PK_1_sqldbm_sold PRIMARY KEY ( ProductKey ),
 CONSTRAINT FK_sqldbm_DimProduct_sqldbm_sold FOREIGN KEY ( ProductKey ) REFERENCES EDW.sqldbm_DimProduct ( ProductKey )
)
COMMENT = 'products can be sold in various Internet sales and internet sales can occur for multiple products';
