-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** sqldbm_30
CREATE TABLE sqldbm_30
(
 ResellerKey   number(38,0) NOT NULL COMMENT 'Reseller identifier',
 BusinessType  varchar(20) NOT NULL,
 ResellerName  varchar(50) NOT NULL,
 OrderMonth    number(38,0),
 ProductLine   varchar(50),
 ETL_ID        timestamp NOT NULL COMMENT 'Table load date', -- From template: "Template_w_etl"
 ETL_TIMESTAMP timestamp_ntz NOT NULL COMMENT 'Table load date TIME', -- From template: "Template_w_etl"

 CONSTRAINT PK_2_sqldbm_30 PRIMARY KEY ( ResellerKey ),
 CONSTRAINT FK_sqldbm_DimReseller_sqldbm_30 FOREIGN KEY ( ResellerKey ) REFERENCES EDW.sqldbm_DimReseller ( ResellerKey )
);
