-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** sqldbm_table_w_warning
CREATE TABLE sqldbm_table_w_warning
(

);
