-- ************************* SqlDBM: Databricks *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** edw.legacy_customer
CREATE VIEW edw.legacy_customer (
  custkey COMMENT 'Unique identification number',
  name COMMENT 'Customer name')
COMMENT 'View for legacy customers with over 5 years of loyalty'
TBLPROPERTIES (
  'transient_lastDdlTime' = '1677522410')
AS SELECT custkey, name
         FROM EDW.customer
        WHERE active_years >= 5
;
