-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: AdWorks project, v952 by serge@sqldbm.com ***


-- ************************************** Account_Type
CREATE OR REPLACE TABLE Account_Type
(
 Account_type_id   integer NOT NULL,
 EtlId             date NOT NULL COMMENT 'hello desc', -- From template: "table_w_etl_fields"
 EtlFilename       varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded', -- From template: "table_w_etl_fields"
 account_type_desc varchar NOT NULL,

 CONSTRAINT PK_Account_Type_Account_type_id PRIMARY KEY ( Account_type_id )
);
