-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** "ADVENTUREWORKSDW.EDW".sqldbm_FactFinance
CREATE TABLE "ADVENTUREWORKSDW.EDW".sqldbm_FactFinance
(
 OrganizationKey    number(38,0) NOT NULL COMMENT 'Organizarion identifier',
 FinanceKey         number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Finance identifier',
 DateKey            number(38,0) NOT NULL COMMENT 'It is the key to join date table',
 DepartmentGroupKey number(38,0) NOT NULL COMMENT 'Department group identifier',
 ScenarioKey        number(38,0) NOT NULL COMMENT 'Scenario Identifier',
 AccountKey         number(38,0) NOT NULL COMMENT 'Account Identifier',
 Amount             float NOT NULL COMMENT 'Amount in Eur',

 CONSTRAINT "FK_${ParentTableName}_${TableName}" FOREIGN KEY ( DateKey ) REFERENCES "ADVENTUREWORKSDW.EDW".sqldbm_DimDate ( DateKey ),
 CONSTRAINT "FK_${ParentTableName}_${TableName}" FOREIGN KEY ( OrganizationKey ) REFERENCES "ADVENTUREWORKSDW.EDW".sqldbm_DimOrganization ( OrganizationKey ),
 CONSTRAINT "FK_${ParentTableName}_${TableName}" FOREIGN KEY ( DepartmentGroupKey ) REFERENCES "ADVENTUREWORKSDW.EDW".sqldbm_DimDepartmentGroup ( DepartmentGroupKey ),
 CONSTRAINT "FK_${ParentTableName}_${TableName}" FOREIGN KEY ( ScenarioKey ) REFERENCES "ADVENTUREWORKSDW.EDW".sqldbm_DimScenario ( ScenarioKey ),
 CONSTRAINT "FK_${ParentTableName}_${TableName}" FOREIGN KEY ( AccountKey ) REFERENCES "ADVENTUREWORKSDW.EDW".sqldbm_DimAccount ( AccountKey )
)
COMMENT = 'Facts for Finance';
