-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** "ADVENTUREWORKSDW.EDW".sqldbm_NewFactCurrencyRate
CREATE TABLE "ADVENTUREWORKSDW.EDW".sqldbm_NewFactCurrencyRate
(
 CurrencyKey  number(38,0) NOT NULL COMMENT 'Currency Identifier',
 AverageRate  float,
 CurrencyID   varchar(3) COMMENT 'Currency Identifier',
 CurrencyDate date,
 EndOfDayRate float COMMENT 'The daily closing rate',
 DateKey      number(38,0) COMMENT 'It is the key to join date table',

 CONSTRAINT "FK_${ParentTableName}_${TableName}" FOREIGN KEY ( CurrencyKey ) REFERENCES "ADVENTUREWORKSDW.EDW".sqldbm_DimCurrency ( CurrencyKey ),
 CONSTRAINT "FK_${ParentTableName}_${TableName}" FOREIGN KEY ( DateKey ) REFERENCES "ADVENTUREWORKSDW.EDW".sqldbm_DimDate ( DateKey )
);
