-- ************************ SqlDBM: Microsoft SQL Server ************************
-- * Generated by SqlDBM: SqlServer sample demo  aug 21, v4 by serge@sqldbm.com *


-- ************************************** [dbo].[Supplier]
CREATE TABLE [dbo].[Supplier]
(
 [SupplierId]  int IDENTITY (1, 1) NOT NULL ,
 [CompanyName] nvarchar(40) NOT NULL ,
 [Phone]       nvarchar(20) NULL ,


 CONSTRAINT [PK_Supplier] PRIMARY KEY CLUSTERED ([SupplierId] ASC),
 CONSTRAINT [AK1_Supplier_CompanyName] UNIQUE NONCLUSTERED ([CompanyName] ASC)
);
GO



EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Basic information 
about Supplier', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Supplier';
GO