-- **********************************************************************
-- ************************* Generated by SqlDBM ************************



-- ************************************** edw.customer_orders

CREATE TABLE edw.customer_orders
(
 custkey       bigint NOT NULL COMMENT 'Customer identifier',
 orderkey      bigint NOT NULL COMMENT 'Order identifier',
 custkey_1     bigint NOT NULL,
 name          string,
 address       string,
 phone         string,
 orderstatus   string,
 totalprice    decimal(18, 2),
 orderdate     date,
 orderpriority string,
 clerk         string
)
USING DELTA
 TBLPROPERTIES (delta.checkpoint.writeStatsAsJson = false, delta.checkpoint.writeStatsAsStruct = true, delta.minReaderVersion = 1, delta.minWriterVersion = 2)
 COMMENT 'It relates the customers and orders table with many to many relationship';
