-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Ivan's first project by ivan.lopez@sqldbm.com *


-- ************************************** EDW.DimAccount_Test
CREATE TABLE EDW.DimAccount_Test
(
 AccountKey                    number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Unique Identifier of the Account data',
 ParentAccountKey              number(38,0) COMMENT 'Identifier of parent Account',
 AccountCodeAlternateKey       number(38,0),
 ParentAccountCodeAlternateKey number(38,0),
 AccountDescription            varchar(50),
 AccountType                   varchar(50),
 Operator                      varchar(50),
 CustomMembers                 varchar(300),
 ValueType                     varchar(50),
 CustomMemberOptions           varchar(200),

 CONSTRAINT PK_DimAccount PRIMARY KEY ( AccountKey )
)
COMMENT = 'Holds all Account information';
