-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Ivan's first project by ivan.lopez@sqldbm.com *


-- ************************************** EDW.DimEmployee
CREATE TABLE EDW.DimEmployee
(
 EmployeeKey                          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 ParentEmployeeKey                    number(38,0),
 EmployeeNationalIDAlternateKey       varchar(15),
 ParentEmployeeNationalIDAlternateKey varchar(15),
 SalesTerritoryKey                    number(38,0),
 FirstName                            varchar(50) NOT NULL,
 LastName                             varchar(50) NOT NULL,
 MiddleName                           varchar(50),
 NameStyle                            number(38,0) NOT NULL,
 Title                                varchar(50),
 HireDate                             date,
 BirthDate                            date,
 LoginID                              varchar(256),
 EmailAddress                         varchar(50),
 Phone                                varchar(25),
 MaritalStatus                        varchar(1),
 EmergencyContactName                 varchar(50),
 EmergencyContactPhone                varchar(25),
 SalariedFlag                         number(38,0),
 Gender                               varchar(1),
 PayFrequency                         number(38,0),
 BaseRate                             number(38,0),
 VacationHours                        number(38,0),
 SickLeaveHours                       number(38,0),
 CurrentFlag                          number(38,0) NOT NULL,
 SalesPersonFlag                      number(38,0) NOT NULL,
 DepartmentName                       varchar(50),
 StartDate                            date,
 EndDate                              date,
 Status                               varchar(50),

 CONSTRAINT PK_DimEmployee PRIMARY KEY ( EmployeeKey ),
 CONSTRAINT FK_DimEmployee_403 FOREIGN KEY ( ParentEmployeeKey ) REFERENCES EDW.DimEmployee ( EmployeeKey ),
 CONSTRAINT FK_DimEmployee_405 FOREIGN KEY ( SalesTerritoryKey ) REFERENCES EDW.DimSalesTerritory ( SalesTerritoryKey )
)
COMMENT = 'This table holds all Employee Information';
