-- ************************* SqlDBM: Databricks *************************
-- ************************* Generated by SqlDBM ************************



-- ************************************** edw.lineitem

CREATE TABLE edw.lineitem
(
 linenumber    int NOT NULL,
 orderkey      bigint NOT NULL,
 custkey       bigint NOT NULL,
 partkey       bigint,
 suppkey       bigint NOT NULL,
 nationkey     bigint NOT NULL,
 quantity      decimal(18, 2),
 extendedprice decimal(18, 2),
 discount      decimal(18, 2),
 tax           decimal(18, 2),
 returnflag    string,
 linestatus    string,
 shipdate      date,
 commitdate    date,
 receiptdate   date,
 shipinstruct  string,
 shipmode      string,
 comment       string
)
USING DELTA
 /* The 'delta.columnMapping.mode' property is added by default to make the alter script work correctly */
 TBLPROPERTIES (delta.checkpoint.writeStatsAsJson = false, delta.checkpoint.writeStatsAsStruct = true, delta.minReaderVersion = 1, delta.minWriterVersion = 2, delta.columnMapping.mode = 'name');
