-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Ivan's first project by ivan.lopez@sqldbm.com *


-- ************************************** EDW.DimOrganization
CREATE TABLE EDW.DimOrganization
(
 OrganizationKey       number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 ParentOrganizationKey number(38,0),
 PercentageOfOwnership varchar(16),
 OrganizationName      varchar(50),
 CurrencyKey           number(38,0),

 CONSTRAINT PK_DimOrganization PRIMARY KEY ( OrganizationKey )
)
COMMENT = 'Dimension for Organizational Data';
