-- **********************************************************************
-- ************************* Generated by SqlDBM ************************



-- ************************************** edw.vip_customer

CREATE TABLE edw.vip_customer
(
 custkey    bigint NOT NULL COMMENT 'Customer identifier',
 vip_points int NOT NULL
)
USING DELTA
 TBLPROPERTIES (delta.checkpoint.writeStatsAsJson = false, delta.checkpoint.writeStatsAsStruct = true, delta.minReaderVersion = 1, delta.minWriterVersion = 2)
;
