-- **********************************************************************
-- ************************* Generated by SqlDBM ************************



-- ************************************** edw.sub_partsupp

CREATE TABLE edw.sub_partsupp
(
 sub_parsupp_key bigint NOT NULL,
 sub_availqty    int,
 sub_supplycost  decimal(18, 2)
)
USING DELTA
 TBLPROPERTIES (delta.checkpoint.writeStatsAsJson = false, delta.checkpoint.writeStatsAsStruct = true, delta.minReaderVersion = 1, delta.minWriterVersion = 2)
;
