-- **********************************************************************
-- ************************* Generated by SqlDBM ************************



-- ************************************** edw.supplier_child

CREATE TABLE edw.supplier_child
(
 suppkey   bigint NOT NULL,
 nationkey bigint NOT NULL,
 address   string,
 phone     string,
 comment   string,
 CONSTRAINT FK_1 FOREIGN KEY (suppkey, nationkey) REFERENCES edw.supplier (suppkey, nationkey)
);
