-- ************************* SqlDBM: Databricks *************************
-- ************************* Generated by SqlDBM ************************



-- ************************************** edw.customer

CREATE TABLE edw.customer
(
 custkey      bigint NOT NULL COMMENT 'Customer identifier',
 name         string COMMENT 'Customer name',
 address      string COMMENT 'Billing address',
 nationkey    bigint COMMENT 'Customer nationality code',
 phone        string COMMENT 'Phone number of the customer',
 acctbal      decimal(18, 2),
 active_years bigint COMMENT 'Since when the customer is registered',
 mktsegment   string COMMENT 'Segment of the client',
 comment      string COMMENT 'Any additional comment about the customer'
)
USING DELTA
 /* The 'delta.columnMapping.mode' property is added by default to make the alter script work correctly */
 TBLPROPERTIES (delta.checkpoint.writeStatsAsJson = false, delta.checkpoint.writeStatsAsStruct = true, delta.minReaderVersion = 1, delta.minWriterVersion = 2, delta.columnMapping.mode = 'name')
 COMMENT 'Customer master data';
