-- **********************************************************************
-- ************************* Generated by SqlDBM ************************



-- ************************************** edw.supplier

CREATE TABLE edw.supplier
(
 suppkey   bigint NOT NULL,
 nationkey bigint NOT NULL,
 name      string,
 address   string,
 phone     string,
 acctbal   decimal(18, 2),
 comment   string,
 CONSTRAINT PK_2 PRIMARY KEY (suppkey, nationkey)
)
USING DELTA
 TBLPROPERTIES (delta.checkpoint.writeStatsAsJson = false, delta.checkpoint.writeStatsAsStruct = true, delta.minReaderVersion = 1, delta.minWriterVersion = 2, Property_demo = 'demo1')
;
