-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** EDW.sqldbm_DimEmployee
CREATE TABLE EDW.sqldbm_DimEmployee
(
 EmployeeKey                          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Employee Identifier',
 ParentEmployeeKey                    number(38,0) COMMENT 'Employee Identifier for the partent relation',
 EmployeeNationalIDAlternateKey       varchar(15) COMMENT 'Employee nationality Identifier',
 ParentEmployeeNationalIDAlternateKey varchar(15) COMMENT 'Employee nationality for the partent relation',
 SalesTerritoryKey                    number(38,0) COMMENT 'SalesTerritory identifier',
 FirstName                            varchar(50) NOT NULL COMMENT 'Name of the employee',
 LastName                             varchar(50) NOT NULL COMMENT 'surname of the employee',
 MiddleName                           varchar(50) COMMENT 'middle name of the employee',
 NameStyle                            number(38,0) NOT NULL COMMENT 'Surname of the employee',
 Title                                varchar(50) COMMENT 'Title of the employee',
 HireDate                             date COMMENT 'The date when the employee hired',
 BirthDate                            date COMMENT 'The birtday of the employee',
 LoginID                              varchar(256),
 EmailAddress                         varchar(50) COMMENT 'e-mail address of the employee',
 Phone                                varchar(25) COMMENT 'Phone number of the employee',
 MaritalStatus                        varchar(1) COMMENT 'Married/Single',
 EmergencyContactName                 varchar(50) COMMENT 'Contact name of emergency needs',
 EmergencyContactPhone                varchar(25) COMMENT 'Contact number of emergency needs',
 SalariedFlag                         number(38,0),
 Gender                               varchar(1) COMMENT 'F/M',
 PayFrequency                         number(38,0) COMMENT 'Daily, Weekly, Monthly',
 BaseRate                             number(38,0),
 VacationHours                        number(38,0) COMMENT 'The amount of the total hours for vacations',
 SickLeaveHours                       number(38,0) COMMENT 'The amount of the total hours for sick leave',
 CurrentFlag                          number(38,0) NOT NULL,
 SalesPersonFlag                      number(38,0) NOT NULL COMMENT 'Is this sales person?',
 DepartmentName                       varchar(50) COMMENT 'The name of the department where the employee works',
 StartDate                            date COMMENT 'Employment start date',
 EndDate                              date COMMENT 'Employment start date',
 Status                               varchar(50) COMMENT 'Employee status',

 CONSTRAINT PK_PK_DimEmployee_sqldbm_DimEmployee PRIMARY KEY ( EmployeeKey ),
 CONSTRAINT FK_sqldbm_DimEmployee_sqldbm_DimEmployee FOREIGN KEY ( ParentEmployeeKey ) REFERENCES EDW.sqldbm_DimEmployee ( EmployeeKey ),
 CONSTRAINT FK_sqldbm_DimSalesTerritory_sqldbm_DimEmployee FOREIGN KEY ( SalesTerritoryKey ) REFERENCES EDW.sqldbm_DimSalesTerritory ( SalesTerritoryKey )
)
COMMENT = 'This table holds all Employee Information';
