-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Ivan's first project by ivan.lopez@sqldbm.com *


-- ************************************** EDW.DimDateClone
CREATE TABLE EDW.DimDateClone
(
 DateKey              number(38,0) NOT NULL,
 FullDateAlternateKey date NOT NULL,
 DayNumberOfWeek      number(38,0) NOT NULL,
 EnglishDayNameOfWeek varchar(10) NOT NULL,
 SpanishDayNameOfWeek varchar(10) NOT NULL,
 FrenchDayNameOfWeek  varchar(10) NOT NULL,
 DayNumberOfMonth     number(38,0) NOT NULL,
 DayNumberOfYear      number(38,0) NOT NULL,
 WeekNumberOfYear     number(38,0) NOT NULL,
 EnglishMonthName     varchar(10) NOT NULL,
 SpanishMonthName     varchar(10) NOT NULL,
 FrenchMonthName      varchar(10) NOT NULL,
 MonthNumberOfYear    number(38,0) NOT NULL,
 CalendarQuarter      number(38,0) NOT NULL,
 CalendarYear         number(38,0) NOT NULL,
 CalendarSemester     number(38,0) NOT NULL,
 FiscalQuarter        number(38,0) NOT NULL,
 FiscalYear           number(38,0) NOT NULL,
 FiscalSemester       number(38,0) NOT NULL,

 CONSTRAINT PK_DimDate PRIMARY KEY ( DateKey )
)
COMMENT = 'Dimension for Date time';
