-- **********************************************************************
-- ************************* Generated by SqlDBM ************************



-- ************************************** edw.partsupp

CREATE TABLE edw.partsupp
(
 partkey    bigint NOT NULL,
 suppkey    bigint NOT NULL,
 availqty   int,
 supplycost decimal(18, 2),
 comment    string
)
USING DELTA
 TBLPROPERTIES (delta.checkpoint.writeStatsAsJson = false, delta.checkpoint.writeStatsAsStruct = true, delta.minReaderVersion = 1, delta.minWriterVersion = 2)
;
