-- **********************************************************************
-- ************************* Generated by SqlDBM ************************



-- ************************************** edw.orders

CREATE TABLE edw.orders
(
 orderkey      bigint NOT NULL,
 custkey       bigint NOT NULL,
 orderstatus   string,
 totalprice    decimal(18, 2),
 orderdate     date,
 orderpriority string,
 clerk         string,
 shippriority  int,
 comment       string
)
USING DELTA
 TBLPROPERTIES (delta.checkpoint.writeStatsAsJson = false, delta.checkpoint.writeStatsAsStruct = true, delta.minReaderVersion = 1, delta.minWriterVersion = 2)
;
