-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Ivan's first project by ivan.lopez@sqldbm.com *


-- ************************************** EDW.DimSalesTerritory
CREATE TABLE EDW.DimSalesTerritory
(
 SalesTerritoryKey          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 SalesTerritoryAlternateKey number(38,0),
 SalesTerritoryRegion       varchar(50) NOT NULL,
 SalesTerritoryCountry      varchar(50) NOT NULL,
 SalesTerritoryGroup        varchar(50),

 CONSTRAINT PK_DimSalesTerritory PRIMARY KEY ( SalesTerritoryKey )
)
COMMENT = 'Sales Territory data';
