-- **********************************************************************
-- ************************* Generated by SqlDBM ************************



-- ************************************** edw.part

CREATE TABLE edw.part
(
 partkey     bigint,
 name        string,
 mfgr        string,
 brand       string,
 type        string,
 size        int,
 container   string,
 retailprice decimal(18, 2),
 comment     string
)
USING DELTA
 TBLPROPERTIES (delta.checkpoint.writeStatsAsJson = false, delta.checkpoint.writeStatsAsStruct = true, delta.minReaderVersion = 1, delta.minWriterVersion = 2)
;
