-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: Awesome Project by daniel.jimenez+team@sqldbm.com *


-- ************************************** EDW.sqldbm_44
CREATE TABLE EDW.sqldbm_44
(
 col_3         varbinary NOT NULL,
 ETL_ID        timestamp NOT NULL COMMENT 'Table load date', -- From template: "Template_w_etl"
 ETL_TIMESTAMP timestamp_ntz NOT NULL COMMENT 'Table load date TIME', -- From template: "Template_w_etl"

 CONSTRAINT PK_1_sqldbm_44 PRIMARY KEY ( col_3 )
);
