-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: Awesome Project by daniel.jimenez+team@sqldbm.com *


-- ************************************** EDW.sqldbm_DimScenario
CREATE TABLE EDW.sqldbm_DimScenario
(
 ScenarioKey   number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Scenario Identifier',
 ScenarioName  varchar(50) COMMENT 'Name of the Scenario',
 CreatedBy     varchar(50) NOT NULL COMMENT 'Who Created this Scenario',
 CreatedDate   timestamp_ntz(9) NOT NULL COMMENT 'Scenario Creation Date',
 UpdatedDate   timestamp_ntz(9) NOT NULL,
 UpdatedBy     varchar(50) NOT NULL,
 test_col      varchar NOT NULL,
 Sample_Column varchar(50) NOT NULL,

 CONSTRAINT PK_DimScenario_sqldbm_DimScenario PRIMARY KEY ( ScenarioKey ),
 CONSTRAINT FK_Sampel_GTable_sqldbm_DimScenario FOREIGN KEY ( Sample_Column ) REFERENCES Sampel_GTable ( Sample_Column )
)
COMMENT = 'Dimension Scenario';
