-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Awesome Project, v133 by hazal.sener@sqldbm.com *


-- ************************************** EDW.sqldbm_FactSurveyResponse
CREATE TABLE EDW.sqldbm_FactSurveyResponse
(
 SurveyResponseKey             number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 DateKey                       number(38,0) NOT NULL COMMENT 'It is the key to join date table',
 CustomerKey                   number(38,0) NOT NULL COMMENT 'Customer Identifier',
 ProductCategoryKey            number(38,0) NOT NULL COMMENT 'Product category identifier',
 EnglishProductCategoryName    varchar(50) NOT NULL COMMENT 'Product category name in English',
 ProductSubcategoryKey         number(38,0) NOT NULL COMMENT 'Product Subcategory identifier',
 EnglishProductSubcategoryName varchar(50) NOT NULL COMMENT 'Product Subcategory name',

 CONSTRAINT FK_sqldbm_DimDate_sqldbm_FactInternetSales FOREIGN KEY ( DateKey ) REFERENCES EDW.sqldbm_DimDate ( DateKey ),
 CONSTRAINT FK_sqldbm_DimDate_sqldbm_FactInternetSales FOREIGN KEY ( ProductCategoryKey ) REFERENCES EDW.sqldbm_DimProductCategory ( ProductCategoryKey )
);
