-- **********************************************************************
-- ************************* Generated by SqlDBM ************************



-- ************************************** edw.region

CREATE TABLE edw.region
(
 regionkey bigint,
 name      string,
 comment   string
)
USING DELTA
 TBLPROPERTIES (delta.checkpoint.writeStatsAsJson = false, delta.checkpoint.writeStatsAsStruct = true, delta.minReaderVersion = 1, delta.minWriterVersion = 2)
;
