-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Ivan's first project by ivan.lopez@sqldbm.com *


-- ************************************** EDW.DimProductCategory
CREATE TABLE EDW.DimProductCategory
(
 ProductCategoryKey          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1,
 ProductCategoryAlternateKey number(38,0),
 EnglishProductCategoryName  varchar(50) NOT NULL,
 SpanishProductCategoryName  varchar(50) NOT NULL,
 FrenchProductCategoryName   varchar(50) NOT NULL,

 CONSTRAINT PK_DimProductCategory PRIMARY KEY ( ProductCategoryKey )
);
