-- **********************************************************************
-- ************************* Generated by SqlDBM ************************



-- ************************************** edw.nation

CREATE TABLE edw.nation
(
 nationkey bigint NOT NULL,
 name      string,
 regionkey bigint,
 comment   string
)
USING DELTA
 TBLPROPERTIES (delta.checkpoint.writeStatsAsJson = false, delta.checkpoint.writeStatsAsStruct = true, delta.minReaderVersion = 1, delta.minWriterVersion = 2)
;
