-- ************************* SqlDBM: Databricks *************************
-- ************************* Generated by SqlDBM ************************



-- ************************************** edw.part

CREATE TABLE edw.part
(
 partkey     bigint,
 name        string,
 mfgr        string,
 brand       string,
 type        string,
 size        int,
 container   string,
 retailprice decimal(18, 2),
 comment     string
)
USING DELTA
 /* The 'delta.columnMapping.mode' property is added by default to make the alter script work correctly */
 TBLPROPERTIES (delta.checkpoint.writeStatsAsJson = false, delta.checkpoint.writeStatsAsStruct = true, delta.minReaderVersion = 1, delta.minWriterVersion = 2, delta.columnMapping.mode = 'name');
