-- ************************** SqlDBM: Snowflake *************************
-- * Generated by SqlDBM: Ivan's first project by ivan.lopez@sqldbm.com *


-- ************************************** EDW.ChildDemo
CREATE TABLE EDW.ChildDemo
(
 ScenarioKey number(38,0) NOT NULL COMMENT 'Scenario Identifier',
 CreatedBy   varchar(50) NOT NULL,
 CreatedDate timestamp_ntz(9) NOT NULL,
 UpdatedDate timestamp_ntz(9) NOT NULL,
 UpdatedBy   varchar(50) NOT NULL,
 TESTCOLUMN  number(38,0) NOT NULL,
 NewCol      number(38,0),

 CONSTRAINT PK_664 PRIMARY KEY ( ScenarioKey ),
 CONSTRAINT FK_661 FOREIGN KEY ( ScenarioKey ) REFERENCES EDW.DimScenario ( ScenarioKey )
);
