-- **********************************************************************
-- ************************* Generated by SqlDBM ************************



-- ************************************** edw.customer

CREATE TABLE edw.customer
(
 custkey      bigint NOT NULL COMMENT 'Customer identifier',
 nationkey    bigint NOT NULL COMMENT 'Customer nationality code',
 name         string COMMENT 'Customer name',
 address      string COMMENT 'Billing address',
 phone        string COMMENT 'Phone number of the customer',
 acctbal      decimal(18, 2),
 active_years bigint COMMENT 'Since when the customer is registered',
 mktsegment   string COMMENT 'Segment of the client',
 comment      string COMMENT 'Any additional comment about the customer',
 CONSTRAINT PK_3 PRIMARY KEY (custkey, nationkey)
)
USING DELTA
 TBLPROPERTIES (delta.checkpoint.writeStatsAsJson = false, delta.checkpoint.writeStatsAsStruct = true, delta.minReaderVersion = 1, delta.minWriterVersion = 2)
 COMMENT 'Customer master data';
