-- ************************* SqlDBM: Databricks *************************
-- ************************* Generated by SqlDBM ************************



-- ************************************** edw.supplier

CREATE TABLE edw.supplier
(
 suppkey   bigint NOT NULL,
 nationkey bigint NOT NULL,
 name      string,
 address   string,
 phone     string,
 acctbal   decimal(18, 2),
 comment   string
)
USING DELTA
 /* The 'delta.columnMapping.mode' property is added by default to make the alter script work correctly */
 TBLPROPERTIES (delta.checkpoint.writeStatsAsJson = false, delta.checkpoint.writeStatsAsStruct = true, delta.minReaderVersion = 1, delta.minWriterVersion = 2, delta.columnMapping.mode = 'name');
