-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: Awesome Project by daniel.jimenez+team@sqldbm.com *


-- ************************************** HOTELBNB.FactProductInventory
CREATE TABLE HOTELBNB.FactProductInventory
(
 ProductKey   number(38,0) NOT NULL,
 DateKey      number(38,0) NOT NULL,
 MovementDate date NOT NULL,
 UnitCost     number(38,0) NOT NULL WITH TAG (EDW.cost_center = 'val_1'),
 UnitsIn      number(38,0) NOT NULL,
 UnitsOut     number(38,0) NOT NULL,
 UnitsBalance number(38,0) NOT NULL,

 CONSTRAINT FK_sqldbm_DimDate_sqldbm_FactInternetSales_copy_1 FOREIGN KEY ( DateKey ) REFERENCES HOTELBNB.DimDate ( DateKey )
);
