-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: Awesome Project by daniel.jimenez+team@sqldbm.com *


-- ************************************** HOTELBNB.DimProductCategory
CREATE TABLE HOTELBNB.DimProductCategory
(
 ProductCategoryKey          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'Product category identifier',
 ProductCategoryAlternateKey number(38,0) COMMENT 'Product category alternate key',
 EnglishProductCategoryName  varchar(50) NOT NULL COMMENT 'Product category name in English',
 SpanishProductCategoryName  varchar(50) NOT NULL COMMENT 'Product category name in Spanish',
 FrenchProductCategoryName   varchar(50) NOT NULL COMMENT 'Product category name in French',

 CONSTRAINT PK_DimProductCategory_sqldbm_copy_1_DimProductCategory PRIMARY KEY ( ProductCategoryKey )
);
