-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: Awesome Project by daniel.jimenez+team@sqldbm.com *


-- ************************************** HOTELBNB.FactInternetSales
CREATE TABLE HOTELBNB.FactInternetSales
(
 OrderDateKey          number(38,0) NOT NULL,
 DueDateKey            number(38,0) NOT NULL,
 ShipDateKey           number(38,0) NOT NULL,
 CustomerKey           number(38,0) NOT NULL,
 PromotionKey          number(38,0) NOT NULL,
 CurrencyKey           number(38,0) NOT NULL,
 SalesTerritoryKey     number(38,0) NOT NULL,
 SalesOrderNumber      varchar(20) NOT NULL,
 SalesOrderLineNumber  number(38,0) NOT NULL,
 RevisionNumber        number(38,0) NOT NULL,
 OrderQuantity         number(38,0) NOT NULL,
 UnitPrice             number(38,0) NOT NULL,
 ExtendedAmount        number(38,0) NOT NULL,
 UnitPriceDiscountPct  float NOT NULL,
 DiscountAmount        float NOT NULL,
 ProductStandardCost   number(38,0) NOT NULL,
 TotalProductCost      number(38,0) NOT NULL,
 SalesAmount           number(38,0) NOT NULL,
 TaxAmt                number(38,0) NOT NULL,
 Freight               number(38,0) NOT NULL,
 CarrierTrackingNumber varchar(25),
 CustomerPONumber      varchar(25),

 CONSTRAINT FK_DimDate_FactInternetSales FOREIGN KEY ( OrderDateKey ) REFERENCES HOTELBNB.DimDate ( DateKey ),
 CONSTRAINT FK_DimDate_FactInternetSales FOREIGN KEY ( DueDateKey ) REFERENCES HOTELBNB.DimDate ( DateKey ),
 CONSTRAINT FK_DimDate_FactInternetSales FOREIGN KEY ( ShipDateKey ) REFERENCES HOTELBNB.DimDate ( DateKey ),
 CONSTRAINT FK_sqldbm_DimDate_sqldbm_FactInternetSales_copy_1 FOREIGN KEY ( CurrencyKey ) REFERENCES HOTELBNB.DimCurrency ( CurrencyKey )
)
COMMENT = 'Fact table to hold Currency Data';
