-- ************************* SqlDBM: Databricks *************************
-- ***** Generated by SqlDBM: Databricks Demo by hzlsener@gmail.com *****

-- ************************************** mySchema.orders
CREATE TABLE mySchema.orders
(
 orderkey      bigint NOT NULL,
 custkey       bigint NOT NULL CONSTRAINT FK_customer REFERENCES mySchema.customer,
 orderstatus   string,
 totalprice    decimal(18, 2),
 orderdate     date,
 orderpriority string,
 clerk         string,
 shippriority  int,
 comment       string,
 CONSTRAINT PK_3_orders PRIMARY KEY (orderkey, custkey)
)
USING DELTA;
