-- ************************* SqlDBM: Databricks *************************
-- ***** Generated by SqlDBM: Databricks Demo by hzlsener@gmail.com *****

-- ************************************** mySchema.part
CREATE TABLE mySchema.part
(
 partkey     bigint,
 name        string,
 mfgr        string,
 brand       string,
 type        string,
 size        int,
 container   string,
 retailprice decimal(18, 2),
 comment     string
)
USING DELTA;
