-- ************************* SqlDBM: Databricks *************************
-- ***** Generated by SqlDBM: Databricks Demo by hzlsener@gmail.com *****

-- ************************************** mySchema.supplier
CREATE TABLE mySchema.supplier
(
 suppkey   bigint NOT NULL,
 nationkey bigint NOT NULL CONSTRAINT FK_nation REFERENCES mySchema.nation,
 name      string,
 address   string,
 phone     string,
 acctbal   decimal(18, 2),
 comment   string,
 CONSTRAINT PK_PK_2_supplier PRIMARY KEY (suppkey, nationkey)
)
USING DELTA;
