-- ************************* SqlDBM: Databricks *************************
-- ***** Generated by SqlDBM: Databricks Demo by hzlsener@gmail.com *****

-- ************************************** mySchema.region
CREATE TABLE mySchema.region
(
 regionkey bigint,
 name      string,
 comment   string
)
USING DELTA;
