-- ************************* SqlDBM: Databricks *************************
-- ***** Generated by SqlDBM: Databricks Demo by hzlsener@gmail.com *****

-- ************************************** mySchema.customer
CREATE TABLE mySchema.customer
(
 custkey      bigint NOT NULL COMMENT 'Customer identifier' CONSTRAINT PK_PK_2_customer PRIMARY KEY,
 name         string COMMENT 'Customer name',
 address      string COMMENT 'Billing address',
 nationkey    bigint COMMENT 'Customer nationality code',
 phone        string COMMENT 'Phone number of the customer',
 acctbal      decimal(18, 2),
 active_years bigint COMMENT 'Since when the customer is registered',
 mktsegment   string COMMENT 'Segment of the client',
 comment      string COMMENT 'Any additional comment about the customer'
)
USING DELTA;
