-- ************************* SqlDBM: Databricks *************************
-- ***** Generated by SqlDBM: Databricks Demo by hzlsener@gmail.com *****

-- ************************************** mySchema.order_lineitem
CREATE TABLE mySchema.order_lineitem
(
 orderkey   bigint NOT NULL,
 custkey    bigint NOT NULL,
 linenumber int NOT NULL CONSTRAINT FK_lineitem REFERENCES mySchema.lineitem,
 CONSTRAINT PK_1_order_lineitem PRIMARY KEY (orderkey, custkey, linenumber),
 CONSTRAINT FK_orders_1 FOREIGN KEY (orderkey, custkey) REFERENCES mySchema.orders (orderkey, custkey)
);
