-- ************************* SqlDBM: Databricks *************************
-- ***** Generated by SqlDBM: Databricks Demo by hzlsener@gmail.com *****

-- ************************************** mySchema.lineitem
CREATE TABLE mySchema.lineitem
(
 linenumber    int NOT NULL CONSTRAINT PK_PK_2_lineitem PRIMARY KEY,
 partkey       bigint,
 suppkey       bigint NOT NULL,
 nationkey     bigint NOT NULL,
 quantity      decimal(18, 2),
 extendedprice decimal(18, 2),
 discount      decimal(18, 2),
 tax           decimal(18, 2),
 returnflag    string,
 linestatus    string,
 shipdate      date,
 commitdate    date,
 receiptdate   date,
 shipinstruct  string,
 shipmode      string,
 comment       string,
 CONSTRAINT FK_supplier FOREIGN KEY (suppkey, nationkey) REFERENCES mySchema.supplier (suppkey, nationkey)
)
USING DELTA;
