-- ************************* SqlDBM: Databricks *************************
-- ***** Generated by SqlDBM: Databricks Demo by hzlsener@gmail.com *****

-- ************************************** mySchema.sub_partsupp
CREATE TABLE mySchema.sub_partsupp
(
 sub_parsupp_key bigint NOT NULL,
 sub_availqty    int,
 sub_supplycost  decimal(18, 2)
);
