-- ************************* SqlDBM: Databricks *************************
-- ***** Generated by SqlDBM: Databricks Demo by hzlsener@gmail.com *****

-- ************************************** mySchema.partsupp
CREATE TABLE mySchema.partsupp
(
 partkey    bigint NOT NULL,
 suppkey    bigint NOT NULL,
 availqty   int,
 supplycost decimal(18, 2),
 comment    string,
 CONSTRAINT PK_PK_2_partsupp PRIMARY KEY (partkey, suppkey)
)
USING DELTA;
