-- ************************* SqlDBM: Databricks *************************
-- ***** Generated by SqlDBM: Databricks Demo by hzlsener@gmail.com *****

-- ************************************** mySchema.nation
CREATE TABLE mySchema.nation
(
 nationkey bigint NOT NULL CONSTRAINT PK_3_nation PRIMARY KEY,
 name      string,
 regionkey bigint,
 comment   string
)
USING DELTA;
