-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: AdWorks project, v947 by serge@sqldbm.com ***


-- ************************************** ProdctSubtype
CREATE OR REPLACE TABLE ProdctSubtype
(
 ProductTypeId    int NOT NULL,
 ProductSubtypeId int NOT NULL,
 EtlId            date NOT NULL COMMENT 'hello desc', -- From template: "table_w_etl_fields"
 EtlFilename      varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded', -- From template: "table_w_etl_fields"
 Name             varchar NOT NULL COMMENT 'subtype name',

 CONSTRAINT PK_ProdctSubtype_ProductSubtypeId_ProductTypeId_3436 PRIMARY KEY ( ProductTypeId, ProductSubtypeId ),
 CONSTRAINT Fk3433 FOREIGN KEY ( ProductTypeId ) REFERENCES ProductType ( ProductTypeId )
);
