-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: AdWorks project, v947 by serge@sqldbm.com ***


-- ************************************** ProductType
CREATE OR REPLACE TABLE ProductType
(
 ProductTypeId int NOT NULL,
 EtlId         date NOT NULL COMMENT 'hello desc', -- From template: "table_w_etl_fields"
 EtlFilename   varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded', -- From template: "table_w_etl_fields"
 ProductName   varchar NOT NULL COMMENT 'comes from CRM',

 CONSTRAINT PK_ProductType_ProductTypeId_3424 PRIMARY KEY ( ProductTypeId )
)
CLUSTER BY ( ProductTypeId, EtlId );
