-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: Awesome Project by daniel.jimenez+team@sqldbm.com *


-- ************************************** Sample_Table
CREATE TABLE Sample_Table
(
 ETL_ID        timestamp NOT NULL COMMENT 'Table load date', -- From template: "Template_w_etl"
 ETL_TIMESTAMP timestamp_ntz NOT NULL COMMENT 'Table load date TIME' -- From template: "Template_w_etl"

);
