-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: Awesome Project by daniel.jimenez+team@sqldbm.com *


-- ************************************** Sampel_GTable
CREATE TABLE Sampel_GTable
(
 ETL_ID        timestamp NOT NULL COMMENT 'Table load date', -- From template: "Template_w_etl"
 ETL_TIMESTAMP timestamp_ntz NOT NULL COMMENT 'Table load date TIME', -- From template: "Template_w_etl"
 Sample_Column varchar(50) NOT NULL,

 CONSTRAINT PK_1_Sampel_GTable PRIMARY KEY ( Sample_Column )
);
