-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Awesome Project, v133 by hazal.sener@sqldbm.com *


-- ************************************** SampleTable
CREATE TABLE SampleTable
(
 ETL_ID        timestamp NOT NULL COMMENT 'Table load date', -- From template: "Template_w_etl"
 ETL_TIMESTAMP timestamp_ntz NOT NULL COMMENT 'Table load date TIME', -- From template: "Template_w_etl"
 SampleColumn  varchar(50) NOT NULL
);
