-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Awesome Project, v133 by hazal.sener@sqldbm.com *


-- ************************************** SFLK_DATA.sqldbm_DimReseller_child
CREATE TABLE SFLK_DATA.sqldbm_DimReseller_child
(
 ResellerKey          number(38,0) NOT NULL COMMENT 'Reseller identifier',
 ResellerAlternateKey varchar(15) COMMENT 'Reseller alternate key',
 BusinessType         varchar(20) NOT NULL,
 ResellerName         varchar(50) NOT NULL,
 NumberEmployees      number(38,0),
 ETL_ID               timestamp NOT NULL COMMENT 'Table load date', -- From template: "Template_w_etl"
 ETL_TIMESTAMP        timestamp_ntz NOT NULL COMMENT 'Table load date TIME', -- From template: "Template_w_etl"

 CONSTRAINT PK_1_sqldbm_DimReseller_child PRIMARY KEY ( ResellerKey ),
 CONSTRAINT FK_sqldbm_DimReseller_sqldbm_DimReseller_child FOREIGN KEY ( ResellerKey ) REFERENCES EDW.sqldbm_DimReseller ( ResellerKey )
);
