-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Awesome Project, v133 by hazal.sener@sqldbm.com *


-- ************************************** SFLK_DATA.sqldbm_template
CREATE TABLE SFLK_DATA.sqldbm_template
(
 ScenarioKey   number(38,0) NOT NULL COMMENT 'Scenario Identifier',
 ETL_ID        timestamp NOT NULL COMMENT 'Table load date', -- From template: "Template_w_etl"
 ETL_TIMESTAMP timestamp_ntz NOT NULL COMMENT 'Table load date TIME', -- From template: "Template_w_etl"

 CONSTRAINT PK_1_sqldbm_template PRIMARY KEY ( ScenarioKey )
);
