-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: Awesome Project by daniel.jimenez+team@sqldbm.com *


-- ************************************** sqldbm_table_w_warning
CREATE TABLE sqldbm_table_w_warning
(

);
