-- ************************** SqlDBM: Snowflake *************************
-- ************************* Generated by SqlDBM ************************


-- ************************************** sqldbm_template_applied
CREATE TABLE sqldbm_template_applied
(
 ProductKey    number(38,0) NOT NULL,
 ETL_ID        timestamp NOT NULL COMMENT 'Table load date', -- From template: "Template_w_etl"
 ETL_TIMESTAMP timestamp_ntz NOT NULL COMMENT 'Table load date TIME', -- From template: "Template_w_etl"

 CONSTRAINT "1_sqldbm_template_applied" PRIMARY KEY ( ProductKey )
);
