-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Awesome Project, v133 by hazal.sener@sqldbm.com *


-- ************************************** sqldbm_31
CREATE TABLE sqldbm_31
(
 ResellerKey   number(38,0) NOT NULL COMMENT 'Reseller identifier',
 ETL_ID        timestamp NOT NULL COMMENT 'Table load date', -- From template: "Template_w_etl"
 ETL_TIMESTAMP timestamp_ntz NOT NULL COMMENT 'Table load date TIME', -- From template: "Template_w_etl"

 CONSTRAINT PK_2_sqldbm_31 PRIMARY KEY ( ResellerKey ),
 CONSTRAINT FK_sqldbm_DimReseller_child_sqldbm_31 FOREIGN KEY ( ResellerKey ) REFERENCES SFLK_DATA.sqldbm_DimReseller_child ( ResellerKey )
);
