-- *************************** SqlDBM: Snowflake **************************
-- * Generated by SqlDBM: Awesome Project, v133 by hazal.sener@sqldbm.com *


-- ************************************** sqldbm_table_w_warning
CREATE TABLE sqldbm_table_w_warning
(

);
