-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: AdWorks project, v954 by serge@sqldbm.com ***


-- ************************************** Table133
CREATE OR REPLACE TABLE Table133
(
 my_pk       integer NOT NULL,
 EtlId       date NOT NULL COMMENT 'hello desc', -- From template: "table_w_etl_fields"
 EtlFilename varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded', -- From template: "table_w_etl_fields"
 "new Col"      NOT NULL,

 CONSTRAINT PK_Table133_my_pk PRIMARY KEY ( my_pk )
);
