-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: AdWorks project, v947 by serge@sqldbm.com ***


-- ************************************** Table117
CREATE OR REPLACE TABLE Table117
(
 new_pk      varchar NOT NULL,
 EtlId       date NOT NULL COMMENT 'hello desc', -- From template: "table_w_etl_fields"
 EtlFilename varchar(50) NOT NULL COMMENT 'source file or table from where the target is loaded', -- From template: "table_w_etl_fields"

 CONSTRAINT PK_Table117_new_pk_1 PRIMARY KEY ( new_pk ),
 CONSTRAINT Fk57 FOREIGN KEY ( new_pk ) REFERENCES Table116 ( new_pk )
);
