-- **********************************************************************
-- ************************* Generated by SqlDBM ************************



-- ************************************** table_14

CREATE TABLE table_14
(
 new_pk   bigint NOT NULL CONSTRAINT PK_1 PRIMARY KEY,
 test_col string NOT NULL
);
