-- ************************* SqlDBM: Databricks *************************
-- ***** Generated by SqlDBM: Databricks Demo by hzlsener@gmail.com *****

-- ************************************** vip_customer
CREATE TABLE vip_customer
(
 custkey    bigint NOT NULL COMMENT 'Customer identifier',
 vip_points integer NOT NULL
);
